/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    ArticleOutlined: typeof import('./src/icons/ArticleOutlined.vue')['default']
    BlogPublishedOn: typeof import('./src/components/BlogPublishedOn.vue')['default']
    BlogsTitle: typeof import('./src/components/BlogsTitle.vue')['default']
    CalCom: typeof import('./src/components/CalCom.vue')['default']
    CvOutlinedIcon: typeof import('./src/icons/CvOutlinedIcon.vue')['default']
    DjangoSkillIcon: typeof import('./src/icons/skill-icon/DjangoSkillIcon.vue')['default']
    FindMe: typeof import('./src/components/FindMe.vue')['default']
    Github: typeof import('./src/icons/Github.vue')['default']
    Hamburger: typeof import('./src/icons/Hamburger.vue')['default']
    LightBulbOutlined: typeof import('./src/icons/LightBulbOutlined.vue')['default']
    Linkedin: typeof import('./src/icons/Linkedin.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    MoonOutlined: typeof import('./src/icons/MoonOutlined.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NextSkillIcon: typeof import('./src/icons/skill-icon/NextSkillIcon.vue')['default']
    NodeSkillIcon: typeof import('./src/icons/skill-icon/NodeSkillIcon.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectExtraCard: typeof import('./src/components/ProjectExtraCard.vue')['default']
    ReactSkillIcon: typeof import('./src/icons/skill-icon/ReactSkillIcon.vue')['default']
    RightArrowOutlined: typeof import('./src/icons/RightArrowOutlined.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideEnterTransition: typeof import('./src/components/SlideEnterTransition.vue')['default']
    SunOutlined: typeof import('./src/icons/SunOutlined.vue')['default']
    TelephoneOutlined: typeof import('./src/icons/TelephoneOutlined.vue')['default']
    ToggleDark: typeof import('./src/components/ToggleDark.vue')['default']
    VueSkillIcon: typeof import('./src/icons/skill-icon/VueSkillIcon.vue')['default']
    WorkExperienceCard: typeof import('./src/components/WorkExperienceCard.vue')['default']
  }
}
