export const blogs = [
  {
    name: 'remembering-polymorphism',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/remembering-polymorphism.md',
    readTime: '8 min',
    title: 'Remembering Polymorphism',
    date: '2026-01-18T22:34:18+05:30',
    tags: ['javascript', 'polymorphism'],
  },
  {
    name: 'upgrading to nuxt 4',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/upgrading%20to%20nuxt%204.md',
    readTime: '7 min',
    title: 'How to Update to Nuxt 4: Complete Upgrade Guide',
    date: '2025-07-27T20:50:14+05:30',
    tags: ['vue', 'nuxt'],
  },
  {
    name: 'Handling event listeners in React',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/Handling%20event%20listeners%20in%20React.md',
    readTime: '2 min',
    title: 'Handling event listeners in React',
    date: '2025-04-09T18:31:36+05:30',
    tags: ['react'],
  },
  {
    name: 'nuxt-layers',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/nuxt-layers.md',
    readTime: '7 min',
    title: 'Nuxt Layers explained',
    date: '2025-03-30T03:44:38+05:30',
    tags: ['vue', 'nuxt', 'nuxt-layers'],
  },
  {
    name: 'attr-in-css',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/attr-in-css.md',
    readTime: '3 min',
    title: 'attr() in css',
    date: '2024-11-07T19:30:32+05:30',
    tags: ['css', 'html'],
  },
  {
    name: "Vue 3's Expose",
    url: "https://raw.githubusercontent.com/Sreesanth46/blogs/main/Vue%203's%20Expose.md",
    readTime: '2 min',
    title: "Vue 3's Expose",
    date: '2024-09-23T03:58:30+05:30',
    tags: ['vue'],
  },
  {
    name: 'some-fancy-bitwise-tricks',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/some-fancy-bitwise-tricks.md',
    readTime: '6 min',
    title: 'Some fancy Bitwise Tricks',
    date: '2024-08-11T01:37:26+05:30',
    tags: ['tricks', 'javascript'],
  },
  {
    name: 'context-manager-in-python',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/context-manager-in-python.md',
    readTime: '5 min',
    title: 'Context manager in Python',
    date: '2024-05-20T19:23:00.000+00:00',
    tags: ['python', 'context-manager'],
  },
  {
    name: 'vue-teleport',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/vue-teleport.md',
    readTime: '3 min',
    title: 'Vue 3 Teleport',
    date: '2024-04-23T17:06:00.000+00:00',
    tags: ['vue'],
  },
  {
    name: 'infinite-scroll',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/infinite-scroll.md',
    readTime: '6 min',
    title: 'How to Implement Infinite Scroll: A Step-by-Step Guide',
    date: '2024-03-21T09:29:00.000+00:00',
    tags: ['react', 'infinite-scroll'],
  },
  {
    name: 'show-component-for-react',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/show-component-for-react.md',
    readTime: '3 min',
    title: 'Show component for React',
    date: '2024-03-21T01:20:00.000+00:00',
    tags: ['react'],
  },
  {
    name: 'vue-render-function',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/vue-render-function.md',
    readTime: '2 min',
    title: 'h() function in Vue',
    date: '2024-03-09T21:05:00.000+00:00',
    tags: ['vue'],
  },
  {
    name: 'user-session-management-in-microservice',
    url: 'https://raw.githubusercontent.com/Sreesanth46/blogs/main/user-session-management-in-microservice.md',
    readTime: '3 min',
    title: 'Efficient User session Management in Microservice Architecture',
    date: '2024-03-02T16:04:00.000+00:00',
    tags: ['micro-service', 'session'],
  },
] as const;
