/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/blogs': RouteRecordInfo<
      '/blogs',
      '/blogs',
      Record<never, never>,
      Record<never, never>,
      | '/blogs/'
      | '/blogs/[slug]'
    >,
    '/blogs/': RouteRecordInfo<
      '/blogs/',
      '/blogs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/[slug]': RouteRecordInfo<
      '/blogs/[slug]',
      '/blogs/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/Projects': RouteRecordInfo<
      '/Projects',
      '/Projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resume': RouteRecordInfo<
      '/resume',
      '/resume',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/blogs.vue': {
      routes:
        | '/blogs'
        | '/blogs/'
        | '/blogs/[slug]'
      views:
        | 'default'
    }
    'src/pages/blogs/index.vue': {
      routes:
        | '/blogs/'
      views:
        | never
    }
    'src/pages/blogs/[slug].vue': {
      routes:
        | '/blogs/[slug]'
      views:
        | never
    }
    'src/pages/Projects.vue': {
      routes:
        | '/Projects'
      views:
        | never
    }
    'src/pages/resume.vue': {
      routes:
        | '/resume'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
